export { Home } from './Home';
export { Admin } from './Admin';
export { PageNotFound } from './PageNotFound';
export { ProductDetail } from './ProductDetail';
export { ProductList } from './ProductList';
export { Contact } from './Contact/Contact';
export { ContactEU } from './Contact/ContactEU';
export { ContactIN } from './Contact/ContactIN';
export { ContactUSA } from './Contact/ContactUSA';
